// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCnqIXjVHlIBB6eWFlUbi_TwcfDlPJt2k',
    appId: '1:701220330992:web:dcd1e8948d18cfe79d1135',
    messagingSenderId: '701220330992',
    projectId: 'facebook-clone-cc684',
    authDomain: 'facebook-clone-cc684.firebaseapp.com',
    storageBucket: 'facebook-clone-cc684.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnxlDpS3y8slPK10-qSTFpf6xRCtU2qis',
    appId: '1:701220330992:android:e356c2a02e9607019d1135',
    messagingSenderId: '701220330992',
    projectId: 'facebook-clone-cc684',
    storageBucket: 'facebook-clone-cc684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDxz_WU8_i0OUny45gmh7XEQ8Ab0-fi0Q',
    appId: '1:701220330992:ios:84edc665775d2cb09d1135',
    messagingSenderId: '701220330992',
    projectId: 'facebook-clone-cc684',
    storageBucket: 'facebook-clone-cc684.appspot.com',
    iosClientId: '701220330992-qo4eo0f688sc87rp89s1f1rp1p81v442.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDxz_WU8_i0OUny45gmh7XEQ8Ab0-fi0Q',
    appId: '1:701220330992:ios:84edc665775d2cb09d1135',
    messagingSenderId: '701220330992',
    projectId: 'facebook-clone-cc684',
    storageBucket: 'facebook-clone-cc684.appspot.com',
    iosClientId: '701220330992-qo4eo0f688sc87rp89s1f1rp1p81v442.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookui',
  );
}
